-- @description DF95: Build IFLS Main Toolbar as importable MenuSet (fix: correct toolbar section names)
-- @version 1.0.1
-- @author DF95 (generated by Reaper DAW Ultimate Assistant)
-- @about
--   Writes toolbar sections using exact names REAPER expects:
--     [Floating toolbar 1 (Toolbar 1)] and [Floating toolbar 1]
--   Output: REAPER\ResourcePath\MenuSets\IFLS_Main.Toolbar.ReaperMenuSet
--
--   After running:
--     Options > Customize menus/toolbars... > select "Floating toolbar 1 (Toolbar 1)" > Import...
--
--   Notes:
--   - Registers referenced scripts as actions to obtain stable _RS... command IDs.
--   - If a script is missing, the button is written inert (cmd "_") but the file remains importable.

local function msg(s) reaper.ShowConsoleMsg(tostring(s) .. "\n") end
local function join(a,b)
  if not a or a=="" then return b end
  local last=a:sub(-1)
  if last=="\\" or last=="/" then return a..b end
  return a.."/"..b
end
local function exists(path)
  local f=io.open(path,"rb")
  if f then f:close(); return true end
  return false
end
local function ensure_dir(path) reaper.RecursiveCreateDirectory(path,0) end

local function ensure_named_command(script_abs_path, sectionID)
  if not exists(script_abs_path) then return nil, "missing: "..script_abs_path end
  local cmdID = reaper.AddRemoveReaScript(true, sectionID, script_abs_path, true)
  if not cmdID or cmdID == 0 then
    return nil, "AddRemoveReaScript failed for: "..script_abs_path
  end
  local name = reaper.ReverseNamedCommandLookup(cmdID)
  if not name or name == "" then
    return nil, "ReverseNamedCommandLookup failed for cmdID="..tostring(cmdID)
  end
  return "_"..name, nil
end

-- CONFIG
local resource = reaper.GetResourcePath()
local scripts_root = join(resource, "Scripts")
local SECTION_MAIN = 0

local buttons = {
  {label="IFLS Beat Control Center", script_rel="IFLS/IFLS/Hubs/IFLS_BeatControlCenter_ImGui.lua"},
  {label="IFLS Artist Hub",         script_rel="IFLS/IFLS/Hubs/IFLS_ArtistHub_ImGui.lua"},
  {label="IFLS SampleGalaxy",       script_rel="IFLS/IFLS/Hubs/IFLS_SampleLibraryHub_ImGui.lua"},
  {label="IFLS Groove & Rhythm",    script_rel="IFLS/IFLS/Hubs/IFLS_PolyRhythmHub_ImGui.lua"},
  {label="IFLS Macros & Scenes",    script_rel="IFLS/IFLS/Hubs/IFLS_SceneHub_ImGui.lua"},
  {label="IFLS FX Brain",           script_rel="IFLS/IFLS/Hubs/IFLS_MasterHub_ImGui.lua"},
  {label="IFLS Diagnostics / Inspector", script_rel="IFLS/DF95/DF95_Diagnostics_Insight_Run.lua"},
}

reaper.ClearConsole()
msg("DF95: Build IFLS Main Toolbar MenuSet (section-name fix)")
msg("ResourcePath: "..resource)

local resolved={}
local ok_count, fail_count = 0, 0
for i,b in ipairs(buttons) do
  local abs = join(scripts_root, b.script_rel)
  local named, err = ensure_named_command(abs, SECTION_MAIN)
  if named then
    ok_count=ok_count+1
    resolved[#resolved+1]={idx=i-1, cmd=named, label=b.label}
    msg(("  OK   %d: %s -> %s"):format(i-1, b.label, named))
  else
    fail_count=fail_count+1
    resolved[#resolved+1]={idx=i-1, cmd="_", label=b.label}
    msg(("  FAIL %d: %s (%s)"):format(i-1, b.label, tostring(err)))
  end
end

local menuSets = join(resource, "MenuSets")
ensure_dir(menuSets)
local out_path = join(menuSets, "IFLS_Main.Toolbar.ReaperMenuSet")

local f=assert(io.open(out_path,"wb"))
f:write("; DF95/IFLS - IFLS Main Toolbar (generated)\n")
f:write("; Import into: Options > Customize menus/toolbars... > Floating toolbar 1 (Toolbar 1) > Import...\n\n")

local function write_section(header)
  f:write("["..header.."]\n")
  f:write("title=IFLS Main\n\n")
  for _,it in ipairs(resolved) do
    f:write(("ACT %d 0 %s\n"):format(it.idx, it.cmd))
    f:write(("ITEM %d %s\n\n"):format(it.idx, it.label))
  end
  f:write("\n")
end

write_section("Floating toolbar 1 (Toolbar 1)")
write_section("Floating toolbar 1")

f:close()

msg("")
msg("Wrote: "..out_path)
msg(("Resolved: %d OK, %d missing"):format(ok_count, fail_count))
msg("")
msg("NEXT STEPS:")
msg("1) Options > Customize menus/toolbars...")
msg("2) Select: Floating toolbar 1 (Toolbar 1)")
msg("3) Click: Import...")
msg("4) Choose: IFLS_Main.Toolbar.ReaperMenuSet")
